### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
dataset: nemo-math
template: llama3
cutoff_len: 8000
max_samples: 25000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /shared/feiyang/saves/l8b-nemo-math-25k-5xlr-e1
logging_steps: 10
save_steps: 500000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 32
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
# template: fewshot
# lang: en
# n_shot: 5
# ### output
# save_dir: saves/sft-open_r1_math-l3b8-1k-eval

# ### eval
# batch_size: 4

# eval_dataset: mmlu
# val_size: 0.1
# per_device_eval_batch_size: 8
# eval_strategy: steps
# eval_steps: 500
